stages:
  - test
  - deploy

Deployment:
  image: ruby:2.4
  stage: deploy
  services:
    db: 
      container_name: db
      networks: 
        - djangonetwork
      web:
        depends_on:
          - db
        links:
          - db:db
        networks:
          - djangonetwork
  networks:
    djangonetwork:
      driver: bridge
  before_script:
    - gem install dpl
    - wget -qO- https://cli-assets.heroku.com/install-ubuntu.sh | sh
  script:
    - dpl --provider=heroku --app=$HEROKU_APPNAME --api-key=$HEROKU_APIKEY
    - export HEROKU_API_KEY=$HEROKU_APIKEY
    - heroku run --app $HEROKU_APPNAME python manage.py migrate
  environment:
    name: production
    url: $HEROKU_APP_HOST